name: E2E Tests Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Node environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
          install-command: bash plotly-custom-build.sh
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 300
