name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    permissions:
      contents: read

    strategy:
      # when one test fails, DO NOT cancel the others
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        browser: ["chrome", "firefox"]
        include:
          - os: "macos-latest"
            browser: "electron"
          - os: "ubuntu-latest"
            browser: "chromium"
          - os: "windows-latest"
            browser: "edge"
        exclude:
          - os: "macos-latest"
            browser: "firefox"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Prepare Node environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "lts/*"

      - name: Clear npm cache (Windows)
        if: runner.os == 'Windows'
        run: npm cache clean --force

      - name: Cypress run
        uses: cypress-io/github-action@948d67d3074f1bbb6379c8bdbb04e95d2f8e593f # v7.4.0
        with:
          browser: ${{ matrix.browser }}
          install-command: bash plotly-custom-build.sh
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 300
