name: Cypress E2E Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    permissions:
      contents: read

    strategy:
      # when one test fails, DO NOT cancel the others
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
        browser: ["chrome", "firefox"]
        include:
          - os: "macos-latest"
            browser: "electron"
          - os: "ubuntu-latest"
            browser: "chromium"
          - os: "windows-latest"
            browser: "edge"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Node environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          install-command: bash plotly-custom-build.sh
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 300
